services:
  db:
    image: postgres:16
    container_name: examapp-db
    environment:
      POSTGRES_USER: exam_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exam_app
    ports:
      - "5432:5432"
    volumes:
      - examapp_pgdata:/var/lib/postgresql/data

volumes:
  examapp_pgdata:
